<?php

/**
 * This is the model base class for the table "empresa".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Empresa".
 *
 * Columns in table "empresa" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $emp_codigo
 * @property string $emp_nombre
 * @property string $emp_unidad
 * @property string $emp_firma_jefe
 * @property string $emp_pie_jefe
 * @property string $emp_firma_docente
 * @property string $emp_pie_docente
 * @property string $emp_firma_director_espel
 * @property string $emp_pie_director_espel
 * @property string $emp_pie2_director_espel
 * @property string $emp_firma_aux
 * @property string $emp_pie_aux
 *
 */
abstract class BaseEmpresa extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'empresa';
	}

	public static function representingColumn() {
		return 'emp_nombre';
	}

	public function rules() {
		return array(
			array('emp_nombre, emp_unidad, emp_firma_jefe, emp_pie_jefe, emp_firma_docente, emp_pie_docente, emp_firma_director_espel, emp_pie_director_espel, emp_pie2_director_espel, emp_firma_aux, emp_pie_aux', 'required'),
			array('emp_nombre, emp_unidad, emp_firma_jefe, emp_pie_jefe, emp_firma_docente, emp_pie_docente, emp_firma_director_espel, emp_pie_director_espel, emp_pie2_director_espel, emp_firma_aux, emp_pie_aux', 'length', 'max'=>100),
			array('emp_nombre, emp_unidad, emp_firma_jefe, emp_pie_jefe, emp_firma_docente, emp_pie_docente, emp_firma_director_espel, emp_pie_director_espel, emp_pie2_director_espel, emp_firma_aux, emp_pie_aux', 'default', 'setOnEmpty' => true, 'value' => null),
			array('emp_codigo, emp_nombre, emp_unidad, emp_firma_jefe, emp_pie_jefe, emp_firma_docente, emp_pie_docente, emp_firma_director_espel, emp_pie_director_espel, emp_pie2_director_espel, emp_firma_aux, emp_pie_aux', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'emp_codigo' => Yii::t('app', 'Emp Codigo'),
			'emp_nombre' => Yii::t('app', 'Emp Nombre'),
			'emp_unidad' => Yii::t('app', 'Emp Unidad'),
			'emp_firma_jefe' => Yii::t('app', 'Emp Firma Jefe'),
			'emp_pie_jefe' => Yii::t('app', 'Emp Pie Jefe'),
			'emp_firma_docente' => Yii::t('app', 'Emp Firma Docente'),
			'emp_pie_docente' => Yii::t('app', 'Emp Pie Docente'),
			'emp_firma_director_espel' => Yii::t('app', 'Emp Firma Director Espel'),
			'emp_pie_director_espel' => Yii::t('app', 'Emp Pie Director Espel'),
			'emp_pie2_director_espel' => Yii::t('app', 'Emp Pie2 Director Espel'),
			'emp_firma_aux' => Yii::t('app', 'Emp Firma Aux'),
			'emp_pie_aux' => Yii::t('app', 'Emp Pie Aux'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('emp_codigo', $this->emp_codigo);
		$criteria->compare('emp_nombre', $this->emp_nombre, true);
		$criteria->compare('emp_unidad', $this->emp_unidad, true);
		$criteria->compare('emp_firma_jefe', $this->emp_firma_jefe, true);
		$criteria->compare('emp_pie_jefe', $this->emp_pie_jefe, true);
		$criteria->compare('emp_firma_docente', $this->emp_firma_docente, true);
		$criteria->compare('emp_pie_docente', $this->emp_pie_docente, true);
		$criteria->compare('emp_firma_director_espel', $this->emp_firma_director_espel, true);
		$criteria->compare('emp_pie_director_espel', $this->emp_pie_director_espel, true);
		$criteria->compare('emp_pie2_director_espel', $this->emp_pie2_director_espel, true);
		$criteria->compare('emp_firma_aux', $this->emp_firma_aux, true);
		$criteria->compare('emp_pie_aux', $this->emp_pie_aux, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}