<?php

/**
 * This is the model base class for the table "actividades".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Actividades".
 *
 * Columns in table "actividades" available as properties of the model,
 * followed by relations of table "actividades" available as properties of the model.
 *
 * @property integer $act_codigo
 * @property integer $con_codigo
 * @property string $act_nombre
 * @property string $act_fecha
 * @property string $act_horas_dictadas
 * @property string $act_horas_act_docente
 * @property string $act_horas_totales_docente
 * @property string $act_valor_pagar
 * @property string $act_valor_total
 *
 * @property Contenido $conCodigo
 */
abstract class BaseActividades extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'actividades';
	}

	public static function representingColumn() {
		return 'act_nombre';
	}

	public function rules() {
		return array(
			array('act_nombre', 'required'),
			array('con_codigo', 'numerical', 'integerOnly'=>true),
			array('act_nombre', 'length', 'max'=>100),
			array('act_horas_dictadas, act_horas_act_docente, act_horas_totales_docente, act_valor_pagar, act_valor_total', 'length', 'max'=>10),
			array('act_fecha', 'safe'),
			array('con_codigo, act_nombre, act_fecha, act_horas_dictadas, act_horas_act_docente, act_horas_totales_docente, act_valor_pagar, act_valor_total', 'default', 'setOnEmpty' => true, 'value' => null),
			array('act_codigo, con_codigo, act_nombre, act_fecha, act_horas_dictadas, act_horas_act_docente, act_horas_totales_docente, act_valor_pagar, act_valor_total', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'conCodigo' => array(self::BELONGS_TO, 'Contenido', 'con_codigo'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'act_codigo' => Yii::t('app', 'Act Codigo'),
			'con_codigo' => Yii::t('app', 'Con Codigo'),
			'act_nombre' => Yii::t('app', 'Act Nombre'),
			'act_fecha' => Yii::t('app', 'Act Fecha'),
			'act_horas_dictadas' => Yii::t('app', 'Act Horas Dictadas'),
			'act_horas_act_docente' => Yii::t('app', 'Act Horas Act Docente'),
			'act_horas_totales_docente' => Yii::t('app', 'Act Horas Totales Docente'),
			'act_valor_pagar' => Yii::t('app', 'Act Valor Pagar'),
			'act_valor_total' => Yii::t('app', 'Act Valor Total'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('act_codigo', $this->act_codigo);
		$criteria->compare('con_codigo', $this->con_codigo);
		$criteria->compare('act_nombre', $this->act_nombre, true);
		$criteria->compare('act_fecha', $this->act_fecha, true);
		$criteria->compare('act_horas_dictadas', $this->act_horas_dictadas, true);
		$criteria->compare('act_horas_act_docente', $this->act_horas_act_docente, true);
		$criteria->compare('act_horas_totales_docente', $this->act_horas_totales_docente, true);
		$criteria->compare('act_valor_pagar', $this->act_valor_pagar, true);
		$criteria->compare('act_valor_total', $this->act_valor_total, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}