<?php

/**
 * This is the model base class for the table "certificados".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Certificados".
 *
 * Columns in table "certificados" available as properties of the model,
 * followed by relations of table "certificados" available as properties of the model.
 *
 * @property integer $cer_codigo
 * @property integer $par_codigo
 * @property integer $cur_codigo
 * @property string $cer_nombre
 * @property string $cer_fecha
 * @property string $cer_carga_usuario
 *
 * @property Participante $parCodigo
 * @property Cursos $curCodigo
 */
abstract class BaseCertificados extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'certificados';
	}

	public static function representingColumn() {
		return 'cer_nombre';
	}

	public function rules() {
		return array(
			array('par_codigo, cur_codigo, cer_nombre, cer_fecha, cer_carga_usuario', 'required'),
			array('par_codigo, cur_codigo', 'numerical', 'integerOnly'=>true),
			array('cer_registro ,cer_nombre, cer_constancia', 'length', 'max'=>100),
			array('cer_carga_usuario', 'length', 'max'=>30),
			array('cer_fecha', 'safe'),
			array('par_codigo, cur_codigo, cer_nombre, cer_fecha, cer_carga_usuario', 'default', 'setOnEmpty' => true, 'value' => null),
			array('cer_codigo, par_codigo, cur_codigo, cer_nombre, cer_fecha, cer_carga_usuario', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'parCodigo' => array(self::BELONGS_TO, 'Participante', 'par_codigo'),
			'curCodigo' => array(self::BELONGS_TO, 'Cursos', 'cur_codigo'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'cer_codigo' => Yii::t('app', 'Cer Codigo'),
			'par_codigo' => Yii::t('app', 'Par Codigo'),
			'cur_codigo' => Yii::t('app', 'Cur Codigo'),
			'cer_nombre' => Yii::t('app', 'Cer Nombre'),
                        'cer_registro' => Yii::t('app', 'Cer Registro'),
                        'cer_constancia' => Yii::t('app', 'Cer Constancia'),
			'cer_fecha' => Yii::t('app', 'Cer Fecha'),
			'cer_carga_usuario' => Yii::t('app', 'Cer Carga Usuario'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('cer_codigo', $this->cer_codigo);
		$criteria->compare('par_codigo', $this->par_codigo);
		$criteria->compare('cur_codigo', $this->cur_codigo);
		$criteria->compare('cer_nombre', $this->cer_nombre, true);
                $criteria->compare('cer_registro', $this->cer_registro, true);
                $criteria->compare('cer_constancia', $this->cer_constancia, true);
		$criteria->compare('cer_fecha', $this->cer_fecha, true);
		$criteria->compare('cer_carga_usuario', $this->cer_carga_usuario, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}