<?php

/**
 * This is the model base class for the table "notas".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Notas".
 *
 * Columns in table "notas" available as properties of the model,
 * followed by relations of table "notas" available as properties of the model.
 *
 * @property integer $not_codigo
 * @property integer $cur_codigo
 * @property integer $ins_codigo
 * @property string $not_nota1
 * @property string $not_nota2
 * @property string $not_final
 * @property string $not_observacion
 *
 * @property Inscripcion $insCodigo
 * @property Cursos $curCodigo
 */
abstract class BaseNotas extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'notas';
	}

	public static function representingColumn() {
		return 'not_nota1';
	}

	public function rules() {
		return array(
			array('not_nota1, not_nota2, not_final', 'required'),
			array('cur_codigo, ins_codigo', 'numerical', 'integerOnly'=>true),
			array('not_nota1, not_nota2, not_final', 'length', 'max'=>10),
			array('not_observacion', 'length', 'max'=>45),
			array('cur_codigo, ins_codigo, not_nota1, not_nota2, not_final, not_observacion', 'default', 'setOnEmpty' => true, 'value' => null),
			array('not_codigo, cur_codigo, ins_codigo, not_nota1, not_nota2, not_final, not_observacion', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'insCodigo' => array(self::BELONGS_TO, 'Inscripcion', 'ins_codigo'),
			'curCodigo' => array(self::BELONGS_TO, 'Cursos', 'cur_codigo'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'not_codigo' => Yii::t('app', 'Not Codigo'),
			'cur_codigo' => Yii::t('app', 'Cur Codigo'),
			'ins_codigo' => Yii::t('app', 'Ins Codigo'),
			'not_nota1' => Yii::t('app', 'Not Nota1'),
			'not_nota2' => Yii::t('app', 'Not Nota2'),
			'not_final' => Yii::t('app', 'Not Final'),
			'not_observacion' => Yii::t('app', 'Not Observacion'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('not_codigo', $this->not_codigo);
		$criteria->compare('cur_codigo', $this->cur_codigo);
		$criteria->compare('ins_codigo', $this->ins_codigo);
		$criteria->compare('not_nota1', $this->not_nota1, true);
		$criteria->compare('not_nota2', $this->not_nota2, true);
		$criteria->compare('not_final', $this->not_final, true);
		$criteria->compare('not_observacion', $this->not_observacion, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}