<?php

/**
 * This is the model base class for the table "tipo_evento".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TipoEvento".
 *
 * Columns in table "tipo_evento" available as properties of the model,
 * followed by relations of table "tipo_evento" available as properties of the model.
 *
 * @property integer $tev_codigo
 * @property string $tev_nombre
 * @property integer $tev_estado
 *
 * @property Planificacion[] $planificacions
 */
abstract class BaseTipoEvento extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tipo_evento';
	}

	public static function representingColumn() {
		return 'tev_nombre';
	}

	public function rules() {
		return array(
			array('tev_nombre, tev_estado', 'required'),
			array('tev_estado', 'numerical', 'integerOnly'=>true),
			array('tev_nombre', 'length', 'max'=>45),
			array('tev_nombre, tev_estado', 'default', 'setOnEmpty' => true, 'value' => null),
			array('tev_codigo, tev_nombre, tev_estado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'planificacions' => array(self::HAS_MANY, 'Planificacion', 'tev_codigo'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'tev_codigo' => Yii::t('app', 'Tev Codigo'),
			'tev_nombre' => Yii::t('app', 'Tev Nombre'),
			'tev_estado' => Yii::t('app', 'Tev Estado'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('tev_codigo', $this->tev_codigo);
		$criteria->compare('tev_nombre', $this->tev_nombre, true);
		$criteria->compare('tev_estado', $this->tev_estado);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}