<?php

/**
 * This is the model base class for the table "grupos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Grupos".
 *
 * Columns in table "grupos" available as properties of the model,
 * followed by relations of table "grupos" available as properties of the model.
 *
 * @property integer $gru_codigo
 * @property integer $cur_codigo
 * @property string $gru_nombre
 * @property string $gru_horario
 *
 * @property Cursos $curCodigo
 * @property Inscripcion[] $inscripcions
 */
abstract class BaseGrupos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'grupos';
	}

	public static function representingColumn() {
		return 'gru_nombre';
	}

	public function rules() {
		return array(
			array('gru_nombre, gru_horario', 'required'),
			array('cur_codigo', 'numerical', 'integerOnly'=>true),
			array('gru_nombre, gru_horario', 'length', 'max'=>45),
			array('cur_codigo, gru_nombre, gru_horario', 'default', 'setOnEmpty' => true, 'value' => null),
			array('gru_codigo, cur_codigo, gru_nombre, gru_horario', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'curCodigo' => array(self::BELONGS_TO, 'Cursos', 'cur_codigo'),
			'inscripcions' => array(self::HAS_MANY, 'Inscripcion', 'gru_codigo'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'gru_codigo' => Yii::t('app', 'Gru Codigo'),
			'cur_codigo' => Yii::t('app', 'Cur Codigo'),
			'gru_nombre' => Yii::t('app', 'Gru Nombre'),
			'gru_horario' => Yii::t('app', 'Gru Horario'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('gru_codigo', $this->gru_codigo);
		$criteria->compare('cur_codigo', $this->cur_codigo);
		$criteria->compare('gru_nombre', $this->gru_nombre, true);
		$criteria->compare('gru_horario', $this->gru_horario, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}