<?php

/**
 * This is the model base class for the table "estado_inscripcion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EstadoInscripcion".
 *
 * Columns in table "estado_inscripcion" available as properties of the model,
 * followed by relations of table "estado_inscripcion" available as properties of the model.
 *
 * @property integer $ein_codigo
 * @property string $ein_nombre
 * @property integer $ein_estado
 *
 * @property Inscripcion[] $inscripcions
 */
abstract class BaseEstadoInscripcion extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'estado_inscripcion';
	}

	public static function representingColumn() {
		return 'ein_nombre';
	}

	public function rules() {
		return array(
			array('ein_nombre, ein_estado', 'required'),
			array('ein_estado', 'numerical', 'integerOnly'=>true),
			array('ein_nombre', 'length', 'max'=>45),
			array('ein_nombre, ein_estado', 'default', 'setOnEmpty' => true, 'value' => null),
			array('ein_codigo, ein_nombre, ein_estado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'inscripcions' => array(self::HAS_MANY, 'Inscripcion', 'ein_codigo'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'ein_codigo' => Yii::t('app', 'Ein Codigo'),
			'ein_nombre' => Yii::t('app', 'Ein Nombre'),
			'ein_estado' => Yii::t('app', 'Ein Estado'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('ein_codigo', $this->ein_codigo);
		$criteria->compare('ein_nombre', $this->ein_nombre, true);
		$criteria->compare('ein_estado', $this->ein_estado);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}