<?php

/**
 * This is the model base class for the table "inscripcion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Inscripcion".
 *
 * Columns in table "inscripcion" available as properties of the model,
 * followed by relations of table "inscripcion" available as properties of the model.
 *
 * @property integer $ins_codigo
 * @property integer $cur_codigo
 * @property integer $ein_codigo
 * @property integer $par_codigo
 * @property integer $gru_codigo
 * @property string $ins_fecha_inscripcion
 * @property string $ins_factura_pago
 * @property string $ins_pago_inscripcion
 * @property string $ins_fecha_pago_inscripcion
 * @property string $ins_pago_auditoria
 * @property string $ins_pago_valor
 *
 * @property Asistencia[] $asistencias
 * @property Grupos $gruCodigo
 * @property Participante $parCodigo
 * @property Cursos $curCodigo
 * @property EstadoInscripcion $einCodigo
 * @property Notas[] $notases
 */
abstract class BaseInscripcion extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inscripcion';
	}

	public static function representingColumn() {
		return 'ins_fecha_inscripcion';
	}

	public function rules() {
		return array(
			array('cur_codigo, ein_codigo, par_codigo, gru_codigo', 'numerical', 'integerOnly'=>true),
			array('ins_factura_pago, ins_pago_auditoria', 'length', 'max'=>45),
			array('ins_pago_inscripcion, ins_pago_valor', 'length', 'max'=>10),
			array('ins_fecha_inscripcion, ins_fecha_pago_inscripcion', 'safe'),
			array('cur_codigo, ein_codigo, par_codigo, gru_codigo, ins_fecha_inscripcion, ins_factura_pago, ins_pago_inscripcion, ins_fecha_pago_inscripcion, ins_pago_auditoria, ins_pago_valor', 'default', 'setOnEmpty' => true, 'value' => null),
			array('ins_codigo, cur_codigo, ein_codigo, par_codigo, gru_codigo, ins_fecha_inscripcion, ins_factura_pago, ins_pago_inscripcion, ins_fecha_pago_inscripcion, ins_pago_auditoria, ins_pago_valor', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'asistencias' => array(self::HAS_MANY, 'Asistencia', 'ins_codigo'),
			'gruCodigo' => array(self::BELONGS_TO, 'Grupos', 'gru_codigo'),
			'parCodigo' => array(self::BELONGS_TO, 'Participante', 'par_codigo'),
			'curCodigo' => array(self::BELONGS_TO, 'Cursos', 'cur_codigo'),
			'einCodigo' => array(self::BELONGS_TO, 'EstadoInscripcion', 'ein_codigo'),
			'notases' => array(self::HAS_MANY, 'Notas', 'ins_codigo'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'ins_codigo' => Yii::t('app', 'Ins Codigo'),
			'cur_codigo' => Yii::t('app', 'Cur Codigo'),
			'ein_codigo' => Yii::t('app', 'Ein Codigo'),
			'par_codigo' => Yii::t('app', 'Par Codigo'),
			'gru_codigo' => Yii::t('app', 'Gru Codigo'),
			'ins_fecha_inscripcion' => Yii::t('app', 'Ins Fecha Inscripcion'),
			'ins_factura_pago' => Yii::t('app', 'Ins Factura Pago'),
			'ins_pago_inscripcion' => Yii::t('app', 'Ins Pago Inscripcion'),
			'ins_fecha_pago_inscripcion' => Yii::t('app', 'Ins Fecha Pago Inscripcion'),
			'ins_pago_auditoria' => Yii::t('app', 'Ins Pago Auditoria'),
			'ins_pago_valor' => Yii::t('app', 'Ins Pago Valor'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('ins_codigo', $this->ins_codigo);
		$criteria->compare('cur_codigo', $this->cur_codigo);
		$criteria->compare('ein_codigo', $this->ein_codigo);
		$criteria->compare('par_codigo', $this->par_codigo);
		$criteria->compare('gru_codigo', $this->gru_codigo);
		$criteria->compare('ins_fecha_inscripcion', $this->ins_fecha_inscripcion, true);
		$criteria->compare('ins_factura_pago', $this->ins_factura_pago, true);
		$criteria->compare('ins_pago_inscripcion', $this->ins_pago_inscripcion, true);
		$criteria->compare('ins_fecha_pago_inscripcion', $this->ins_fecha_pago_inscripcion, true);
		$criteria->compare('ins_pago_auditoria', $this->ins_pago_auditoria, true);
		$criteria->compare('ins_pago_valor', $this->ins_pago_valor, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}