<?php

/**
 * This is the model base class for the table "planificacion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Planificacion".
 *
 * Columns in table "planificacion" available as properties of the model,
 * followed by relations of table "planificacion" available as properties of the model.
 *
 * @property integer $pla_codigo
 * @property integer $tca_codigo
 * @property integer $tev_codigo
 * @property string $pla_programa
 * @property string $pla_nombre
 * @property string $pla_fecha_inicio
 * @property string $pla_fecha_fin
 * @property string $pla_lugar
 * @property string $pla_curso_codigo
 * @property string $pla_antecedentes
 * @property string $pla_objetivo
 * @property string $pla_metodologia
 * @property string $pla_presupuesto
 * @property string $pla_disposiciones
 * @property string $pla_firma_supervisado
 * @property string $pla_pie_supervisado
 * @property string $pla_fecha
 * @property string $pla_creado_por
 * @property string $pla_fecha_creacion
 * @property string $pla_modificado_por
 * @property string $pla_fecha_modificacion
 *
 * @property Anexos[] $anexoses
 * @property Cursos[] $cursoses
 * @property ObjetivosEspecificos[] $objetivosEspecificoses
 * @property TipoCapacitacion $tcaCodigo
 * @property TipoEvento $tevCodigo
 * @property Temario[] $temarios
 */
abstract class BasePlanificacion extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'planificacion';
	}

	public static function representingColumn() {
		return 'pla_programa';
	}

	public function rules() {
		return array(
			array('pla_programa, pla_nombre, pla_fecha_inicio, pla_fecha_fin, pla_lugar, pla_curso_codigo, pla_antecedentes, pla_objetivo, pla_metodologia, pla_presupuesto, pla_disposiciones, pla_firma_supervisado, pla_pie_supervisado, pla_fecha, pla_certificacion_presupuestaria, pla_instructivo', 'required'),
			array('tca_codigo, tev_codigo', 'numerical', 'integerOnly'=>true),
			array('pla_nombre, pla_lugar, pla_firma_supervisado, pla_pie_supervisado', 'length', 'max'=>100),
                        array('pla_objetivo', 'length', 'max'=>200),
			array('pla_curso_codigo, pla_creado_por, pla_modificado_por, pla_certificacion_presupuestaria, pla_instructivo', 'length', 'max'=>45),
			array('pla_presupuesto', 'length', 'max'=>10),
			array('pla_programa, pla_fecha_inicio, pla_fecha_fin, pla_antecedentes, pla_metodologia, pla_disposiciones, pla_fecha, pla_fecha_creacion, pla_fecha_modificacion', 'safe'),
			array('tca_codigo, tev_codigo, pla_programa, pla_nombre, pla_fecha_inicio, pla_fecha_fin, pla_lugar, pla_curso_codigo, pla_antecedentes, pla_objetivo, pla_metodologia, pla_presupuesto, pla_disposiciones, pla_firma_supervisado, pla_pie_supervisado, pla_fecha, pla_creado_por, pla_fecha_creacion, pla_modificado_por, pla_fecha_modificacion, pla_certificacion_presupuestaria, pla_instructivo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('pla_codigo, tca_codigo, tev_codigo, pla_programa, pla_nombre, pla_fecha_inicio, pla_fecha_fin, pla_lugar, pla_curso_codigo, pla_antecedentes, pla_objetivo, pla_metodologia, pla_presupuesto, pla_disposiciones, pla_firma_supervisado, pla_pie_supervisado, pla_fecha, pla_creado_por, pla_fecha_creacion, pla_modificado_por, pla_fecha_modificacion, pla_certificacion_presupuestaria, pla_instructivo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'anexoses' => array(self::HAS_MANY, 'Anexos', 'pla_codigo'),
			'cursoses' => array(self::HAS_MANY, 'Cursos', 'pla_codigo'),
			'objetivosEspecificoses' => array(self::HAS_MANY, 'ObjetivosEspecificos', 'pla_codigo'),
			'tcaCodigo' => array(self::BELONGS_TO, 'TipoCapacitacion', 'tca_codigo'),
			'tevCodigo' => array(self::BELONGS_TO, 'TipoEvento', 'tev_codigo'),
			'temarios' => array(self::HAS_MANY, 'Temario', 'pla_codigo'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'pla_codigo' => Yii::t('app', 'Pla Codigo'),
			'tca_codigo' => Yii::t('app', 'Tca Codigo'),
			'tev_codigo' => Yii::t('app', 'Tev Codigo'),
			'pla_programa' => Yii::t('app', 'Pla Programa'),
			'pla_nombre' => Yii::t('app', 'Pla Nombre'),
			'pla_fecha_inicio' => Yii::t('app', 'Pla Fecha Inicio'),
			'pla_fecha_fin' => Yii::t('app', 'Pla Fecha Fin'),
			'pla_lugar' => Yii::t('app', 'Pla Lugar'),
			'pla_curso_codigo' => Yii::t('app', 'Pla Curso Codigo'),
			'pla_antecedentes' => Yii::t('app', 'Pla Antecedentes'),
			'pla_objetivo' => Yii::t('app', 'Pla Objetivo'),
			'pla_metodologia' => Yii::t('app', 'Pla Metodologia'),
			'pla_presupuesto' => Yii::t('app', 'Pla Presupuesto'),
			'pla_disposiciones' => Yii::t('app', 'Pla Disposiciones'),
			'pla_firma_supervisado' => Yii::t('app', 'Pla Firma Supervisado'),
			'pla_pie_supervisado' => Yii::t('app', 'Pla Pie Supervisado'),
			'pla_fecha' => Yii::t('app', 'Pla Fecha'),
			'pla_creado_por' => Yii::t('app', 'Pla Creado Por'),
			'pla_fecha_creacion' => Yii::t('app', 'Pla Fecha Creacion'),
			'pla_modificado_por' => Yii::t('app', 'Pla Modificado Por'),
			'pla_fecha_modificacion' => Yii::t('app', 'Pla Fecha Modificacion'),
                        'pla_certificacion_presupuestaria' => Yii::t('app', 'Pla Certificacin Presupuestaria'),
			'pla_instructivo' => Yii::t('app', 'Pla Instructivo'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('pla_codigo', $this->pla_codigo);
		$criteria->compare('tca_codigo', $this->tca_codigo);
		$criteria->compare('tev_codigo', $this->tev_codigo);
		$criteria->compare('pla_programa', $this->pla_programa, true);
		$criteria->compare('pla_nombre', $this->pla_nombre, true);
		$criteria->compare('pla_fecha_inicio', $this->pla_fecha_inicio, true);
		$criteria->compare('pla_fecha_fin', $this->pla_fecha_fin, true);
		$criteria->compare('pla_lugar', $this->pla_lugar, true);
		$criteria->compare('pla_curso_codigo', $this->pla_curso_codigo, true);
		$criteria->compare('pla_antecedentes', $this->pla_antecedentes, true);
		$criteria->compare('pla_objetivo', $this->pla_objetivo, true);
		$criteria->compare('pla_metodologia', $this->pla_metodologia, true);
		$criteria->compare('pla_presupuesto', $this->pla_presupuesto, true);
		$criteria->compare('pla_disposiciones', $this->pla_disposiciones, true);
		$criteria->compare('pla_firma_supervisado', $this->pla_firma_supervisado, true);
		$criteria->compare('pla_pie_supervisado', $this->pla_pie_supervisado, true);
		$criteria->compare('pla_fecha', $this->pla_fecha, true);
		$criteria->compare('pla_creado_por', $this->pla_creado_por, true);
		$criteria->compare('pla_fecha_creacion', $this->pla_fecha_creacion, true);
		$criteria->compare('pla_modificado_por', $this->pla_modificado_por, true);
		$criteria->compare('pla_fecha_modificacion', $this->pla_fecha_modificacion, true);
                $criteria->compare('pla_certificacion_presupuestaria', $this->pla_certificacion_presupuestaria, true);
		$criteria->compare('pla_instructivo', $this->pla_instructivo, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}