<?php

/**
 * This is the model base class for the table "objetivos_especificos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ObjetivosEspecificos".
 *
 * Columns in table "objetivos_especificos" available as properties of the model,
 * followed by relations of table "objetivos_especificos" available as properties of the model.
 *
 * @property integer $obj_codigo
 * @property integer $pla_codigo
 * @property string $obj_especifico
 *
 * @property Planificacion $plaCodigo
 */
abstract class BaseObjetivosEspecificos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'objetivos_especificos';
	}

	public static function representingColumn() {
		return 'obj_especifico';
	}

	public function rules() {
		return array(
			array('obj_especifico', 'required'),
			array('pla_codigo', 'numerical', 'integerOnly'=>true),
			array('obj_especifico', 'length', 'max'=>300),
			array('pla_codigo, obj_especifico', 'default', 'setOnEmpty' => true, 'value' => null),
			array('obj_codigo, pla_codigo, obj_especifico', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'plaCodigo' => array(self::BELONGS_TO, 'Planificacion', 'pla_codigo'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'obj_codigo' => Yii::t('app', 'Obj Codigo'),
			'pla_codigo' => Yii::t('app', 'Pla Codigo'),
			'obj_especifico' => Yii::t('app', 'Obj Especifico'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('obj_codigo', $this->obj_codigo);
		$criteria->compare('pla_codigo', $this->pla_codigo);
		$criteria->compare('obj_especifico', $this->obj_especifico, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}