<?php

/**
 * This is the model base class for the table "docente".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Docente".
 *
 * Columns in table "docente" available as properties of the model,
 * followed by relations of table "docente" available as properties of the model.
 *
 * @property integer $doc_codigo
 * @property string $doc_cedula
 * @property string $doc_nombre
 * @property string $doc_apellido
 * @property string $doc_siglas
 * @property string $doc_titulo
 * @property string $doc_correo
 * @property string $doc_telefono
 *
 * @property InformeFinal[] $informeFinals
 * @property Temario[] $temarios
 */
abstract class BaseDocente extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'docente';
	}

	public static function representingColumn() {
		return 'doc_cedula';
	}

	public function rules() {
		return array(
			array('doc_cedula, doc_nombre, doc_apellido, doc_siglas, doc_titulo, doc_correo, doc_telefono', 'required'),
			array('doc_cedula', 'length', 'max'=>10),
			array('doc_nombre, doc_apellido', 'length', 'max'=>60),
			array('doc_siglas', 'length', 'max'=>5),
			array('doc_titulo', 'length', 'max'=>45),
			array('doc_correo', 'length', 'max'=>100),
			array('doc_telefono', 'length', 'max'=>15),
			array('doc_cedula, doc_nombre, doc_apellido, doc_siglas, doc_titulo, doc_correo, doc_telefono', 'default', 'setOnEmpty' => true, 'value' => null),
			array('doc_codigo, doc_cedula, doc_nombre, doc_apellido, doc_siglas, doc_titulo, doc_correo, doc_telefono', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'informeFinals' => array(self::HAS_MANY, 'InformeFinal', 'doc_codigo'),
			'temarios' => array(self::HAS_MANY, 'Temario', 'doc_codigo'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'doc_codigo' => Yii::t('app', 'Doc Codigo'),
			'doc_cedula' => Yii::t('app', 'Doc Cedula'),
			'doc_nombre' => Yii::t('app', 'Doc Nombre'),
			'doc_apellido' => Yii::t('app', 'Doc Apellido'),
			'doc_siglas' => Yii::t('app', 'Doc Siglas'),
			'doc_titulo' => Yii::t('app', 'Doc Titulo'),
			'doc_correo' => Yii::t('app', 'Doc Correo'),
			'doc_telefono' => Yii::t('app', 'Doc Telefono'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('doc_codigo', $this->doc_codigo);
		$criteria->compare('doc_cedula', $this->doc_cedula, true);
		$criteria->compare('doc_nombre', $this->doc_nombre, true);
		$criteria->compare('doc_apellido', $this->doc_apellido, true);
		$criteria->compare('doc_siglas', $this->doc_siglas, true);
		$criteria->compare('doc_titulo', $this->doc_titulo, true);
		$criteria->compare('doc_correo', $this->doc_correo, true);
		$criteria->compare('doc_telefono', $this->doc_telefono, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}